export * from './favoriteController.service';
import { FavoriteControllerService } from './favoriteController.service';
export * from './filmController.service';
import { FilmControllerService } from './filmController.service';
export * from './genreController.service';
import { GenreControllerService } from './genreController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './viewController.service';
import { ViewControllerService } from './viewController.service';
export const APIS = [FavoriteControllerService, FilmControllerService, GenreControllerService, UserControllerService, ViewControllerService];
