/**
 * App API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: snapshot
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilmDTO } from './filmDTO';


export interface ApiResponseFilmDTO { 
    result?: FilmDTO;
    errorCode?: string;
    message?: object;
    responseCode?: number;
}

