/**
 * App API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: snapshot
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { Like } from './like';
import { Actor } from './actor';
import { Director } from './director';
import { Genre } from './genre';
import { Dislike } from './dislike';


export interface Film { 
    id?: number;
    title?: string;
    description?: string;
    maturity?: number;
    slug?: string;
    ratingStar?: number;
    genres?: Array<Genre>;
    createdAt?: string;
    updatedAt?: string;
    actors?: Array<Actor>;
    director?: Director;
    likes?: Array<Like>;
    dislikes?: Array<Dislike>;
    comments?: Array<Comment>;
}

