/**
 * App API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: snapshot
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Favorite } from './favorite';


export interface User { 
    id?: number;
    username?: string;
    firstName?: string;
    lastName?: string;
    avatar?: string;
    gender: string;
    birthOfDate?: string;
    mobile?: string;
    password?: string;
    role?: string;
    email?: string;
    favorites?: Array<Favorite>;
}

