/**
 * App API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: snapshot
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewDTO } from './viewDTO';
import { FavoriteDTO } from './favoriteDTO';


export interface UserDTO { 
    id?: number;
    username: string;
    fullName: string;
    gender: string;
    birthOfDate: string;
    firstName: string;
    lastName: string;
    mobile: string;
    password: string;
    role?: string;
    email: string;
    views?: Array<ViewDTO>;
    favorites?: Array<FavoriteDTO>;
}

